# Generated by Django 4.1.3 on 2022-12-11 23:23

import campaigns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('urls', models.CharField(max_length=1000, validators=[campaigns.validators.validate_urls])),
                ('results_per_search', models.PositiveIntegerField(default=100)),
                ('uploaded_csv_file', models.FileField(blank=True, null=True, upload_to=None, validators=[campaigns.validators.validate_csv_file])),
                ('retries', models.PositiveIntegerField(default=0)),
                ('proxies', models.CharField(help_text='List of proxies to use for the request', max_length=1000, validators=[campaigns.validators.validate_proxies])),
                ('parse_all_tables', models.BooleanField(default=False)),
                ('runned', models.BooleanField(default=False, help_text='True if the campaigned was runned at least once')),
                ('paused', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
