# Generated by Django 4.1.3 on 2022-12-11 23:55

import campaigns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='proxies',
            field=models.CharField(blank=True, help_text='List of proxies to use for the request', max_length=1000, null=True, validators=[campaigns.validators.validate_proxies]),
        ),
    ]
