# Generated by Django 4.1.3 on 2022-12-12 19:15

import campaigns.utils
import campaigns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_proxies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='uploaded_csv_file',
        ),
        migrations.AddField(
            model_name='campaign',
            name='csv_file',
            field=models.FileField(blank=True, help_text="A file used to parse a list of urls. Should have 'website' header", null=True, upload_to=campaigns.utils.upload_file_to, validators=[campaigns.validators.validate_csv_file]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parse_all_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='section_to_parse',
            field=models.CharField(blank=True, help_text='Only parse a specific section of the given HTML page', max_length=100, null=True),
        ),
    ]
