# Generated by Django 4.1.3 on 2022-12-13 11:04

import campaigns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_uploaded_csv_file_campaign_csv_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('web_request', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], default='GET', max_length=100)),
                ('runned', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='proxies',
            field=models.CharField(blank=True, help_text='List of proxies provided by the user for the request', max_length=1000, null=True, validators=[campaigns.validators.validate_proxies]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='actions',
            field=models.ManyToManyField(blank=True, to='campaigns.action'),
        ),
    ]
