# Generated by Django 4.1.3 on 2022-12-13 13:40

import campaigns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_action_alter_campaign_proxies_campaign_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['name', 'created_on']},
        ),
        migrations.AlterField(
            model_name='action',
            name='url',
            field=models.URLField(max_length=1000, validators=[campaigns.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='action',
            name='web_request',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], default='GET', max_length=100),
        ),
    ]
