import { library } from '@fortawesome/fontawesome-svg-core'
import { faArrowLeft, faArrowRight, faBell, faBoltLightning, faCircleInfo, faCloud, faCloudArrowUp, faCog, faEye, faHome, faHourglassStart, faICursor, faPlay, faStar, faStop, faTable, faUpload } from '@fortawesome/free-solid-svg-icons'

library.add(faPlay)
library.add(faStop)
library.add(faBell)
library.add(faCog)
library.add(faHome)
library.add(faTable)
library.add(faHourglassStart)
library.add(faICursor)
library.add(faUpload)
library.add(faArrowLeft)
library.add(faArrowRight)
library.add(faCloud)
library.add(faCloudArrowUp)
library.add(faBoltLightning)
library.add(faStar)
library.add(faCircleInfo)
library.add(faEye)
